spring:
  application:
    name: auth

  datasource:
    url: jdbc:mysql://localhost:3306/auth_test?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none

jwt:
  secret: fjaisdpfjsadoifhsiodhvpashi390u190141333h487vvasdlvasdv
  expiration: 2592000000

#logging:
#  level:
#    org.springframework.security: trace